services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev # 開発プロファイルをアクティブにする (DevTools など)
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - ./backend:/app/backend # ホストのbackendディレクトリを、コンテナの/app/backendにマウント(DevToolsによるホットリロードのため)
      - ./frontend/dist:/app/static # ビルドされたフロントエンドファイルをマウント
      - ./build:/app/build # ホストのbuildディレクトリを、コンテナの/app/buildにマウント(コンパイルされたクラスファイルなどをDevToolsが参照できるようにするため)
      - ./build/libs/todo-api-0.0.1-SNAPSHOT.jar:/app/app.jar # ホストのJARを、コンテナの/app/app.jarにマウント(コンテナ起動時に、JARファイルを実行するため)
    working_dir: /app
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data # ホストのdb_dataボリュームをコンテナのデータ領域にマウント
volumes:
  db_data: # 名前付きボリュームを定義

